[package]
name = "slope-macros"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
alkanes-runtime = { path = "../../reference/alkanes-rs/crates/alkanes-runtime" }
metashrew-support = { git = "https://github.com/sandshrewmetaprotocols/metashrew" }