# Chadson v69.0.0: Systematic Task Completion
#
# This file configures the Trunk build tool for the slope-ski frontend.
#
# Current Task: Rebuild the slope-ski frontend from scratch.
# Step: Fix static asset serving.

[serve]
address = "127.0.0.1"
port = 8081

